# Generated by Django 5.2.5 on 2025-10-04 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploads',
            options={'verbose_name': 'Upload', 'verbose_name_plural': 'Uploads'},
        ),
    ]
